### ISSUE TITLE
BufferSession regresses code

### ISSUE THREAD

**Issue by grant-d** [k2workflow/Clay#212]
### Expected Behavior

This pattern is ubiquitous in the consumers of `BufferSession`.

```C#
var rented = BufferSession.RentBuffer(maxLen);
var count = Encoding.UTF8.GetBytes(json, 0, json.Length, rented, 0); <-- rented
```

### Actual Behavior

Since PR #210 this now fails since the final call expects an array of `byte[]` but `BufferSession` no longer exposes such a member.

Note that `.ToArray()` is not a valid mitigation since that would incur perf & GC overhead that would negate the benefits of buffer pooling.

**Comment by jcdickinson** [comment]
`BufferSession.Result.Array`

**Comment by grant-d** [comment]
Ok, I misread the code and it looked like .Array was not delineated.
